In [3]:
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html


Looking in links: https://download.pytorch.org/whl/torch_stable.html
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491070 sha256=79e52539421332ad1d9b808a98b1e45280b5e9705462473221c645516d7f1ecc
  Stored in directory: c:\users\ittaste\appdata\local\pip\cache\wheels\8e\70\28\3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
Successfully built future


In [70]:
import torch
import numpy as np

In [47]:
t1 = torch.tensor([4.])

In [48]:
t1.shape


torch.Size([1])

In [8]:
t1.dtype

torch.float32

In [13]:
k =4.6

In [14]:
type(k)

float

In [12]:
type(t1)

torch.Tensor

In [31]:
t2 = torch.tensor([1., 2, 3, 4,5])

In [36]:
print(t2.ndim)
t2.shape

1


torch.Size([5])

In [26]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])

In [28]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [33]:
t3.shape

torch.Size([3, 2])

In [35]:
t3.ndim

2

In [42]:
#3 dimenssional array
t4 = torch.tensor([
 [[2,3,4], 
 [4,7,5]],
 [[5,8,7], 
 [4,6,7]]])

In [44]:
print(t4.shape)
t4.ndim

torch.Size([2, 2, 3])


3

In [49]:
t1.shape

torch.Size([1])

In [50]:
#create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [57]:
# Arithmetic operations
y = w * x + b
y
#using .backwrd to access the auto gradient function

tensor(17., grad_fn=<AddBackward0>)

In [58]:
y.backward()

In [59]:
w.grad

tensor(6.)

In [60]:
b.grad

tensor(4.)

In [63]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(6.)
dy/db: tensor(4.)


In [64]:
#tensor functions


In [65]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [67]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [69]:
torch.cat([t6, t3])

tensor([[42., 42.],
        [42., 42.],
        [42., 42.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [79]:
#linear regression using SGD
#inputs
inputs = np.array([[73,67,43],
          [91,88,64],
          [87,134,58],
          [102,43,37],
          [69,96,70]], dtype ='float32')
                   

In [80]:
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [84]:
yields = np.array([
    [56,70],
    [81,101],
    [119,133],
    [22,37],
    [103,119], 
], dtype ='float32')

In [85]:
yields

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [77]:
yields.dtype

dtype('int32')

In [86]:
#making numpy arrays to tensor
inputs = torch.from_numpy(inputs)
yields = torch.from_numpy(yields)

In [87]:
yields.ndim

2

In [88]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.1897,  1.3556, -0.4686],
        [ 0.4000, -0.1889,  0.2567]], requires_grad=True)
tensor([-0.8902,  0.4861], requires_grad=True)


In [89]:
def model(x):
    return x @w.t() + b #.t()-> transpose

In [90]:
print(model)

<function model at 0x0000027F12A70F70>


In [148]:
preds = model(inputs)

In [149]:
print(preds)

tensor([[ 75.0282,  46.6767],
        [ 94.3992,  61.2147],
        [156.7856,  54.3500],
        [ 50.7426,  60.5958],
        [ 98.7993,  51.7768]], grad_fn=<AddBackward0>)


In [138]:
print(preds)

tensor([[ 75.0282,  46.6767],
        [ 94.3992,  61.2147],
        [156.7856,  54.3500],
        [ 50.7426,  60.5958],
        [ 98.7993,  51.7768]], grad_fn=<AddBackward0>)


In [93]:
print(yields)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [104]:
#MSE 
def mse (k1,k2):
    diff = k1-k2
    return torch.sum(diff*diff)/diff.numel()

In [122]:
#compute loss using
loss = mse(preds, yields)
print(loss)

tensor(3133.9976, grad_fn=<DivBackward0>)


In [124]:
#computing gradient descents
#copmute gradiesnt
loss.backward

<bound method Tensor.backward of tensor(3133.9976, grad_fn=<DivBackward0>)>

In [125]:
#gradients for weights
print(w)
print(w.grad)

tensor([[ 0.1897,  1.3556, -0.4686],
        [ 0.4000, -0.1889,  0.2567]], requires_grad=True)
tensor([[ 2594.7803,  2620.8142,  1514.3921],
        [-4805.7163, -6291.9224, -3671.4341]])


In [127]:
#looking into the weight elements to know if its positive or negative to effect lr additins


In [143]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    

In [154]:
#vcerifying if loss gets lower
loss = mse(preds, yields)
print(loss)

tensor(1620.1523, grad_fn=<DivBackward0>)


In [156]:
#before proceeding we reset gradient to zero by .zero_( method
#we accumate gradients)
#if not empty new gradient will bw accumulated nd may be ismatching


In [157]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


Train the model using gradient descent
As seen above, we reduce the loss and improve our model using the gradient descent optimization algorithm. Thus, we can train the model using the following steps:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

Let's implement the above step by step.

In [159]:
#generating predictions
preds = model(inputs)
print(preds)

tensor([[ 75.0282,  46.6767],
        [ 94.3992,  61.2147],
        [156.7856,  54.3500],
        [ 50.7426,  60.5958],
        [ 98.7993,  51.7768]], grad_fn=<AddBackward0>)


In [160]:
#calculate the loss
loss = mse(preds, yields)
print(loss)

tensor(1620.1523, grad_fn=<DivBackward0>)


In [161]:
#compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 1707.5244,  1669.9897,   927.3497],
        [-2879.4475, -4208.3335, -2388.6870]])
tensor([ 18.9510, -37.0772])


In [162]:
#updating the weight and biases usig grad computed above
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [163]:
print(w), print(b)

tensor([[ 0.1207,  1.2864, -0.5081],
        [ 0.5249, -0.0210,  0.3540]], requires_grad=True)
tensor([-0.8928,  0.4913], requires_grad=True)


(None, None)

In [164]:
print(b)

tensor([-0.8928,  0.4913], requires_grad=True)


In [167]:
# another phase
# Calculate loss
preds = model(inputs)
loss = mse(preds, yields)
print(loss)

tensor(1271.1565, grad_fn=<DivBackward0>)


In [170]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 1422.6584,  1365.1045,   739.0721],
        [-2262.7290, -3538.7498, -1977.0029]])
tensor([ 15.5756, -29.7448])


In [171]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [172]:
print(w)
print(b)

tensor([[ 0.1065,  1.2728, -0.5155],
        [ 0.5475,  0.0144,  0.3738]], requires_grad=True)
tensor([-0.8929,  0.4916], requires_grad=True)


In [182]:
preds = model(inputs) # this gene´ratzepredictions
loss = mse(preds, yields) # this generate the loss functions
loss.backward() # this generate the gradient descent( loss functions)
print(w.grad)
print(b.grad)
print(w)
print(b)
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5


tensor([[  804.3856,   704.2802,   330.8964],
        [ -928.1915, -2084.1147, -1083.8682]])
tensor([  8.2527, -13.8641])
tensor([[ 0.0827,  1.2505, -0.5272],
        [ 0.5827,  0.0742,  0.4065]], requires_grad=True)
tensor([-0.8932,  0.4920], requires_grad=True)


In [192]:
preds = model(inputs) # this gene´ratzepredictions
loss = mse(preds, yields) # this generate the loss functions
loss.backward() # this generate the gradient descent( loss functions)
print(w.grad)
print(b.grad)
print(w)
print(b)
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

tensor([[ 332.9548,  203.2930,   21.1538],
        [  76.5511, -970.5517, -404.0930]])
tensor([ 12.3967, -14.9448])
tensor([[ 0.0507,  1.2240, -0.5383],
        [ 0.6115,  0.1591,  0.4489]], requires_grad=True)
tensor([-0.8935,  0.4925], requires_grad=True)


In [188]:
print(preds)

tensor([[ 63.8575,  70.5592],
        [ 79.8116,  92.8073],
        [139.6227,  93.1640],
        [ 39.3195,  82.6442],
        [ 85.0336,  83.0767]], grad_fn=<AddBackward0>)


In [185]:
#compute the loss
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()


In [193]:
print(preds)

tensor([[ 61.6702,  75.0904],
        [ 76.9825,  98.8640],
        [136.3147, 101.0411],
        [ 36.9950,  86.3133],
        [ 82.4286,  89.3768]], grad_fn=<AddBackward0>)


In [194]:
print(yields)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [200]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, yields)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [198]:
preds

tensor([[ 58.3314,  73.1760],
        [ 74.9727, 100.3704],
        [133.2682, 129.0327],
        [ 27.9210,  52.9782],
        [ 85.1677, 109.3973]], grad_fn=<AddBackward0>)

In [199]:
yields

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [201]:
print(preds)
print(yields)

tensor([[ 58.0595,  71.9660],
        [ 75.5065,  99.6490],
        [132.4913, 132.6186],
        [ 26.4126,  45.9555],
        [ 86.9766, 112.2404]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [202]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, yields)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
print(preds)
print(yields)

tensor([[ 57.8845,  71.3160],
        [ 76.0489,  99.3417],
        [131.5388, 134.3625],
        [ 25.4620,  42.1918],
        [ 88.4751, 113.9020]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [203]:
#using building neural network
inputs = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70],
    [74,66,43],
    [91, 87, 65],
    [88, 134, 59], 
    [101, 44, 37], 
    [68, 96, 71], 
    [73, 66, 44], 
    [92, 87, 64], 
    [87, 135, 57], 
    [103, 43, 36], 
     [68, 97, 70]], 
   dtype='float32')

In [204]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [206]:
#making numpy to tensor
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [208]:
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


In [209]:
#using datasets loader
#dataloadr do have inputs and taget together as tuples, the providethen in batches for usages
#datasets contains tuple of input and outputs
from torch.utils.data import TensorDataset

In [216]:
train_ds = TensorDataset(inputs, targets)

In [220]:
from torch.utils.data import DataLoader

In [221]:

train_dl = DataLoader(train_ds, batch_size = 5 , shuffle = True)

In [225]:
for x, y in train_dl:
    print(x)
    print(y)

    break

tensor([[103.,  43.,  36.],
        [ 91.,  87.,  65.],
        [ 69.,  96.,  70.],
        [ 68.,  97.,  70.],
        [ 87., 135.,  57.]])
tensor([[ 20.,  38.],
        [ 80., 102.],
        [103., 119.],
        [102., 120.],
        [118., 134.]])


In [231]:
#model is automatically call using nn.linear
import torch.nn as nn
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)
#using list(model.paramer) produces matrix of W and b in the model

Parameter containing:
tensor([[-0.1484, -0.5734,  0.5503],
        [ 0.5417, -0.0968, -0.3921]], requires_grad=True)
Parameter containing:
tensor([-0.2256,  0.2434], requires_grad=True)


In [236]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1484, -0.5734,  0.5503],
         [ 0.5417, -0.0968, -0.3921]], requires_grad=True),
 Parameter containing:
 tensor([-0.2256,  0.2434], requires_grad=True)]

In [238]:
#generating predictions
preds = model(inputs)
preds

tensor([[-2.5812e+01,  1.6444e+01],
        [-2.8967e+01,  1.5928e+01],
        [-5.8050e+01,  1.1663e+01],
        [-1.9657e+01,  3.6828e+01],
        [-2.6987e+01,  8.8357e-01],
        [-2.5387e+01,  1.7082e+01],
        [-2.7843e+01,  1.5633e+01],
        [-5.7648e+01,  1.1813e+01],
        [-2.0082e+01,  3.6190e+01],
        [-2.6288e+01, -5.0274e-02],
        [-2.4688e+01,  1.6149e+01],
        [-2.8542e+01,  1.6567e+01],
        [-5.9173e+01,  1.1959e+01],
        [-2.0355e+01,  3.7762e+01],
        [-2.7412e+01,  2.4511e-01]], grad_fn=<AddmmBackward>)

In [247]:
#loss function using 
import torch.nn.functional as F
loss = F.mse_loss(preds, targets)
print(loss)
loss_fn = F.mse_loss

tensor(10722.1299, grad_fn=<MseLossBackward>)


In [241]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [248]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [270]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 0.9470
Epoch [20/100], Loss: 1.0958
Epoch [30/100], Loss: 0.9873
Epoch [40/100], Loss: 1.4695
Epoch [50/100], Loss: 1.5695
Epoch [60/100], Loss: 0.9671
Epoch [70/100], Loss: 0.9352
Epoch [80/100], Loss: 1.1686
Epoch [90/100], Loss: 0.9399
Epoch [100/100], Loss: 0.9563


In [271]:
model(inputs)

tensor([[ 56.9236,  70.4317],
        [ 82.0874, 100.4719],
        [118.1837, 132.8397],
        [ 20.8297,  37.7599],
        [101.8994, 118.4332],
        [ 55.6792,  69.3508],
        [ 81.9485, 100.5607],
        [118.4831, 133.4354],
        [ 22.0740,  38.8408],
        [103.0049, 119.6029],
        [ 56.7847,  70.5205],
        [ 80.8430,  99.3910],
        [118.3225, 132.7508],
        [ 19.7242,  36.5902],
        [103.1437, 119.5141]], grad_fn=<AddmmBackward>)

In [254]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])